name: food_delivery
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  design_assets:
    path: packages/design_assets

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  smooth_page_indicator: ^1.2.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

# Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  # android_12:
  #   image: assets/android12splash.png
  #   color: "#42a5f5"
  #   icon_background_color: "#eeeeee"
  # fullscreen: true


flutter_intl:
  enabled: true
  main_locale: en
